import {
  Alignment,
  Autoformat,
  Autosave,
  BlockQuote,
  Bold,
  CKFinderUploadAdapter,
  CloudServices,
  EasyImage,
  Essentials,
  FindAndReplace,
  FontBackgroundColor,
  FontColor,
  FontFamily,
  FontSize,
  Heading,
  Highlight,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  ImageTextAlternative,
  Indent,
  IndentBlock,
  Italic,
  Link,
  List,
  ListProperties,
  MediaEmbed,
  Mention,
  ClassicEditor,
  PageBreak,
  Paragraph,
  PasteFromOffice,
  PictureEditing,
  RemoveFormat,
  Strikethrough,
  Subscript,
  Superscript,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  TodoList,
  Underline,
  Undo,
} from 'ckeditor5';
import {
  AnnotationsUIs,
  Comments,
  MergeFields,
  TrackChanges,
  TrackChangesData,
  WideSidebar,
} from 'ckeditor5-premium-features';

import { PluginLinkingExample } from '@authorium/ckeditor5-plugin-linking-example';

import 'ckeditor5/ckeditor5.css';

const LICENSE_KEY = import.meta.env.VITE_CKE_LICENSE_KEY

ClassicEditor
	.create( document.getElementById( 'editor' ), {
		licenseKey: LICENSE_KEY,
		plugins: [
			Alignment,
			AnnotationsUIs,
			Autoformat,
			BlockQuote,
			Autosave,
			Bold,
			CloudServices,
			Comments,
			Essentials,
			EasyImage,
			FindAndReplace,
			FontBackgroundColor,
			FontColor,
			FontFamily,
			FontSize,
			Heading,
			Highlight,
			HorizontalLine,
			Image,
			ImageCaption,
			ImageResize,
			ImageStyle,
			ImageToolbar,
			ImageUpload,
			ImageTextAlternative,
			Indent,
			IndentBlock,
			Italic,
			Link,
			List,
			ListProperties,
			MediaEmbed,
			MergeFields,
			Mention,
			PageBreak,
			Paragraph,
			PasteFromOffice,
			PictureEditing,
			RemoveFormat,
			Strikethrough,
			Subscript,
			Superscript,
			Table,
			TableCaption,
			TableCellProperties,
			TableColumnResize,
			TableProperties,
			TableToolbar,
			TextTransformation,
			TodoList,
			TrackChanges,
			TrackChangesData,
			Underline,
			CKFinderUploadAdapter,
			Undo,
			WideSidebar,
			PluginLinkingExample,
		],
		toolbar: [
			'undo',
			'redo',
			'|',
			'pluginLinkingExampleButton',
			'|',
			'heading',
			'|',
			'bold',
			'italic',
			'link',
			'code',
			'bulletedList',
			'numberedList',
			'|',
			'outdent',
			'indent',
			'|',
			'uploadImage',
			'blockQuote',
			'insertTable',
			'mediaEmbed',
			'codeBlock'
		],
		image: {
			toolbar: [
				'imageStyle:inline',
				'imageStyle:block',
				'imageStyle:side',
				'|',
				'imageTextAlternative'
			]
		},
		table: {
			contentToolbar: [
				'tableColumn',
				'tableRow',
				'mergeTableCells'
			]
		}
	} )
	.then( editor => {
		window.editor = editor;
		window.console.log( 'CKEditor 5 is ready.', editor );
	} )
	.catch( err => {
		window.console.error( err.stack );
	} );